Software/Apiario/Apiario/Controllers/ClienteController.cs
using Apiario.Context;
using Apiario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apiario.Controllers
{
    public class ClienteController : Controller
    {

        private ClienteContext dbCliente = new ClienteContext();
        private ApiarioContext dbApiario = new ApiarioContext();
        private CaixaContext dbCaixa = new CaixaContext();
        private DadosApiarioContext dbDadosApiario = new DadosApiarioContext();
        private DadosCaixaContext dbDadosCaixa = new DadosCaixaContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastrar() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Cliente cliente) 
        {
            if(ModelState.IsValid)
            {
                dbCliente.Clientes.Add(cliente);
                dbCliente.SaveChanges();
                ViewData["Mensagem"] = "Cadastrado com sucesso!";
            }
            return View();
        }


        public ActionResult CadastrarApiario()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CadastrarApiario(String localizacao, String quantasCaixas, String quantasVezes, String hora)
        {
            if (ModelState.IsValid)
            {
                Models.Apiario apiario = new Models.Apiario();
                apiario.localizacao = localizacao;
                apiario.quantasVezes = Int32.Parse(quantasVezes);
                apiario.hora = TimeSpan.Parse(hora);
                apiario.idCliente = Int32.Parse(Session["clienteLogadoID"].ToString());
                dbApiario.Apiarios.Add(apiario);
                dbApiario.SaveChanges();



                for (int i = 0; i < Int32.Parse(quantasCaixas); i++)
                {
                    Caixa caixa = new Caixa();
                    caixa.situacao = "Desativada";
                    caixa.idApiario = apiario.idApiario;
                    dbCaixa.Caixas.Add(caixa);
                    dbCaixa.SaveChanges();

                }

                ViewData["Mensagem"] = "Apiário cadastrado com sucesso!";
            }

            return View();
        }

        public ActionResult Monitoramento(int idApiario) 
        {
            IEnumerable<Models.DadosApiario> dadosApiario = dbDadosApiario.DadosApiario.Where(x => x.idApiario == idApiario);
            ViewBag.idApiario = idApiario;

            return View(dadosApiario);
        }

        public ActionResult VisualizarCaixas(int idApiario)
        {
            ViewBag.idApiario = idApiario;
            IEnumerable<Models.Caixa> caixas = dbCaixa.Caixas.Where(x => x.idApiario == idApiario);

            return View(caixas);
        }

        public ActionResult MonitorarCaixas(int idCaixa)
        {
            Caixa caixa = dbCaixa.Caixas.Find(idCaixa);
            ViewBag.idApiario = caixa.idApiario;
            IEnumerable<Models.DadosCaixa> dadosCaixa = dbDadosCaixa.DadosCaixa.Where(x => x.idCaixa == idCaixa);

            return View(dadosCaixa);
        }

        public ActionResult VisualizarApiario()
        {
            int id = Int32.Parse(Session["clienteLogadoID"].ToString());
            IEnumerable<Models.Apiario> apiario = dbApiario.Apiarios.Where(x => x.idCliente ==id);

            return View(apiario.ToList());
        }

        public ActionResult RemoverApiario()
        {
            
            int id = Int32.Parse(Session["clienteLogadoID"].ToString());
            IEnumerable<Models.Apiario> apiario = dbApiario.Apiarios.Where(x => x.idCliente == id);

            return View(apiario.ToList());
        }

        [HttpGet]
        public ActionResult DeletarApiario(int idApiario)
        {
            dbApiario.Apiarios.Remove(dbApiario.Apiarios.Find(idApiario));
            dbApiario.SaveChanges();

            return RedirectToAction("RemoverApiario");
        }

        public ActionResult Deslogar() 
        {
            Session["clienteLogadoID"] = null;
            return RedirectToAction("../Logar");
        }


	}
}

Software/Apiario/Apiario/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apiario.Controllers
{
    public class InicioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sobre()
        {

            return View();
        }

        public ActionResult Contato()
        {

            return View();
        }
    }
}

Software/Apiario/Apiario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Apiário</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Apiário", "Index", "Inicio", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Inicio")</li>
                    <li>@Html.ActionLink("Sobre", "Sobre", "Inicio")</li>
                    <li>@Html.ActionLink("Contato", "Contato", "Inicio")</li>
                    <li>@Html.ActionLink("Cadastrar","Cadastrar","Cliente")</li>
                    <li>@Html.ActionLink("Logar", "Index", "Logar")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Apiário</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</body>
</html>

Software/Apiario/Apiario/Views/Shared/_LayoutAdmin.cshtml
@if (Session["adminLogadoID"] == null && Session["clienteLogadoID"] == null || Session["clienteLogadoID"] != null)
{
    Response.Redirect("Logar");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Apiário</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administrador", "Index", "Administrador", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Administrador")</li>
                    <li>@Html.ActionLink("Cadastrar Administrador", "Cadastrar", "Administrador")</li>
                    <li>@Html.ActionLink("Gerenciar Apiário", "GerenciarApiario", "Administrador")</li>
                    <li>@Html.ActionLink("Gerenciar Cliente", "GerenciarCliente", "Administrador")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a>Bem Vindo: @Session["adminLogadoNome"]</a></li>
                    <li>@Html.ActionLink("Deslogar", "Deslogar", "Administrador")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Apiário</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</body>
</html>

Software/Apiario/Apiario/Views/Shared/_LayoutCliente.cshtml
@if(Session["clienteLogadoID"] == null && Session["adminLogadoID"] == null || Session["adminLogadoID"] != null)
{
    Response.Redirect("Logar");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Apiário</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cliente", "Index", "Cliente", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Visualizar Apiário", "VisualizarApiario", "Cliente")</li>
                    <li>@Html.ActionLink("Remover Apiário", "RemoverApiario", "Cliente")</li>
                    <li>@Html.ActionLink("Cadastrar Apiário", "CadastrarApiario", "Cliente")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a>Bem Vindo: @Session["clienteLogadoNome"]</a></li>
                    <li>@Html.ActionLink("Deslogar", "Deslogar", "Cliente")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Apiário</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</body>
</html>